### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [barrackHa/hello_qiskit#1]
I recently came across your project hello_qiskit and I noticed that the repository github.com/barrackHa/hello_qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by barrackHa** [comment]
Thanks @cbjuan. Originally It wasn't really meant to be an OS project, just a simple personal project for playing around... Still I [added the license](https://github.com/barrackHa/hello_qiskit/pull/2) and I appreciate the feedback. 
I'll close the issue and please LMK if have any other thoughts. 

Thank you.

**Comment by cbjuan** [comment]
Thank you!
